all: main
.PHONY: all

main:
	gcc -Wall diskget.c -g -o ./bin/diskget.o
	gcc -Wall diskinfo.c -g -o ./bin/diskinfo.o
	gcc -Wall diskput.c -g -o ./bin/diskput.o
	gcc -Wall disklist.c -g -o ./bin/disklist.o